config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root "homes#top"
  get "home/about" => "homes#about"

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  resources :books

  resources :chats, only: [:create, :show]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user

end

app/models/chat.rb
class Chat < ApplicationRecord

  validates :message, presence: true
  belongs_to :user
  belongs_to :room

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  

  #フォローする
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  #フォローされる
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(weight, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/nc209714.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [weight, height]).processed
  end
  
GUEST_USER_EMAIL = "guest@example.con"
  
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end


  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user = User.find(book.user_id)
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :user_authentication, only: [:show]

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = Chat.new(chat_params)
    @chat.user_id = current_user.id
    render :validater unless @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def user_authentication
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new_book.html.erb
<div class="container">
  <h2>New book</h2>
  <%= form_with model: Book.new, url: books_path, method: :post, local: true do |f| %>
    <div class="field">
      <%= f.label :title, "Title" %><br />
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="field mt-3">
      <%= f.label :body, "Opinion" %><br />
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit "Create Book", class: "btn btn-success mt-3" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-md-8 col-sm-10 mx-auto px-4">
    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
      <strong class="h3">
      <%= @book.errors.count %>errors prohibited this obj from being saved:
      </strong>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with model: @book, local: true do |f| %>
      <div class="field">
        <%= f.label :title, "Title" %><br />
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="field mt-2">
        <%= f.label :body, "Opinion" %><br />
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Update Book", class: "btn btn-success my-3" %>
      </div>
    <% end %>

    <div class="d-flex">
      <%= link_to "Show", book_path(@book.id) %>
      <p class="px-2">|</p>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <strong class="h3">
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  </strong>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="row">
  <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <%= render "books/new_book" %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>

        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <%= render "books/new_book" %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%=link_to user_path(@user.id), method: :get do %>
            <%= image_tag @book.user.get_profile_image(100,100) %></br><%= @book.user.name %>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @user == current_user %>
            <td><%= link_to "Edit", edit_book_path, method: :get, class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path, method: :delete, class: "btn  btn-sm btn-danger", data: {confirm: "削除しますか？"} %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: right;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<h1 id="room"><%= @user.name %>さんとのチャット</h1>

<div class="message">
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
</div>


<%= form_with model: @chat, data: {remote: true} do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
<% end %>

app/views/chats/validater.js.erb
$(".errors").html("<%= j(render "layouts/errors", obj: @chat) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto  p-4">
      <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers !!</strong></h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-10 col-sm-11 mx-auto px-4">
      <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers !!</strong></h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!</p>
      <div class="container mx-auto">
        <%= link_to "guest rog in", users_guest_sign_in_path, class: "btn btn-block  btn-sm btn-secondary mt-4", method: :post %>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-block  btn-sm btn-info mt-4" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-block btn-sm btn-success mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <p class="col text-center p-4">CopyRight infratop.inc</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="bg-dark">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a href="/" class="navbar-brand">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ml-auto">
          <% if !user_signed_in? %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-right-to-bracket"></i> Log in
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-link"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fa-solid fa-right-to-bracket"></i> Log out
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Second</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/867c591370.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

  <div class="Notification">
   <% flash.each do |key, value| %>
   <%= content_tag :div, value, class: key %>
   <% end %>
  </div>
  <div class="containar p-4">
    <%= yield %>
  </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/relationships/_follow_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "リムーブ", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォロー", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#btn_<%= @user.id %>").html("<%= j(render "relationships/follow_btn", user: @user) %>");

app/views/relationships/destroy.js.erb
$("#btn_<%= @user.id %>").html("<%= j(render "relationships/follow_btn", user: @user) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render "users/index", users: @users %>
<% else %>
 <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render "users/index", users: @users %>
<% else %>
 <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(50,50) %>
        </td>
        <td><%= user.name %></td>
        <td id="btn_<%= user.id %>">
          <%= render "relationships/follow_btn", user: user %>
        </td>
        <td><%= link_to "Show", user_path(user.id), method: :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user_info.html.erb
<div class="container">
  <h2>User info</h2>
    <div>
      <%= image_tag user.get_profile_image(100, 100) %>
    </div>
  <table class="table">
    <tr>
      <th>name</th>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <th>follows</th>
      <td id="follow_counts">
        <%= link_to user.followings.count, user_followings_path(user) %>
      </td>
    </tr>
    <tr>
      <th>followers</th>
      <td id="follower_counts">
        <%= link_to user.followers.count, user_followers_path(user) %>
      </td>
    </tr>
  </table>
  <% unless user.guest_user? %>
    <% if current_user != user %>
      <div id="btn_<%= user.id %>">
        <%= render "relationships/follow_btn", user: user %>
      </div>
    <% else %>
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary w-100" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    <% end %>
  <% end %>

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to "DM", chat_path(user.id), class: "ml-3" %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-md-8 col-sm-10 mx-auto px-4">
    <h1>User info</h1>

    <% if @user.errors.any? %>
      <strong class="h3">
      <%= @user.errors.count %>errors prohibited this obj from being saved:
      </strong>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with model: @user, local: true do |f| %>
      <div class="field">
        <%= f.label :name, "Name" %><br />
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :profile_image, "image" %><br />
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>

      <div class="field">
        <%= f.label :introduction, "introduction" %><br />
        <%= f.text_area :introduction, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Update User", class: "btn btn-secondary my-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <%= render "books/new_book" %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <div>
      <%= render "index", users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render "users/user_info", user: @user %>
    <%= render "books/new_book" %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="1"></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>